require "gitlab_coverage_viewer/engine"
require "gitlab_coverage_viewer/coverage_formatter/simple_cov_json_formatter"
require "gitlab_coverage_viewer/coverage_formatter/php_unit_clover_formatter"

module GitlabCoverageViewer
end
